<?php

namespace App\Guards;

use App\Events\JWTGuard\Attempting;
use App\Events\JWTGuard\Invalidating;
use Tymon\JWTAuth\Facades\JWTAuth;
use Tymon\JWTAuth\JWTGuard;

/**
 * Created by PhpStorm.
 * User: darevski
 * Date: 15.12.17
 * Time: 0:48
 */

/**
 * Class JWTGuardCorrected
 *
 * Реализация связи Guard(jwt) и Sentinel, через реализацию собственного защитника и JWTAuth
 * Напрямую JWTGuard и Sentinel не ворк
 * TODO: провести нагрузочное тестирование, проверить не наебнется ли всё к ебеням, если наебнеться уйти от событий
 *
 * @package App\Guards
 */
class JWTGuardCorrected extends JWTGuard
{
    public function attempt(array $credentials = [], $login = true)
    {
        //event(new Attempting($credentials));
        return parent::attempt($credentials, $login);
    }

    public function logout($forceForever = false)
    {
        //event(new Invalidating());
        parent::logout($forceForever); // TODO: Change the autogenerated stub
    }
}